### ISSUE TITLE
[DOCS] Move new feature RST to 12.1 docs folder

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#225] opened 2022-10-11 07:03 UTC
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/39a4d9c2ddb4d89c272db2e852d1dbe92133a467)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[DOCS] Move new feature RST to 12.1 docs folder

Resolves: #98575
Related: #97747
Releases: main
Change-Id: If0c5dca5574a1bb6842e6c1c45e14cbfac171389
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76086
Tested-by: Chris Müller <typo3@krue.ml>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Chris Müller <typo3@krue.ml>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Feature-97747-IntroduceMailerInterface.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-97747-1654691279

===========================================
Feature: #97747 - Introduce MailerInterface
===========================================

See :issue:`97747`

Description
===========

To be able to use your own custom MailerInterface implementation in the TYPO3 core, an
interface :php:`TYPO3\CMS\Core\Mail\MailerInterface` is introduced, which extends
:php:`Symfony\Component\Mailer\MailerInterface`

By default :php:`TYPO3\CMS\Core\Mail\Mailer` is registered as implementation in `Service.yaml`.

Example
^^^^^^^

.. code-block:: php

    $mailer = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Mail\MailerInterface::class);

Impact
======

This change makes it possible to create your own :php:`My\Custom\Mailer` that implements
:php:`TYPO3\CMS\Core\Mail\MailerInterface` which is used by TYPO3 core. Therefore it is recommended
to use the interface :php:`TYPO3\CMS\Core\Mail\MailerInterface`, to let dependency injection inject the
desired implementation for every :php:`TYPO3\CMS\Core\Mail\MailerInterface`.

Add the following line in :file:`Configuration/Services.yaml`, to ensure that your custom
implementation can be injected.

.. code-block:: yaml

    TYPO3\CMS\Core\Mail\MailerInterface:
      alias: My\Custom\Mailer

.. index:: PHP-API, ext:core

```

</details>

**Comment by brotkrueml** [comment] 2022-10-11 07:26
Duplicate of #224

**Closed as completed by brotkrueml** 2022-10-11 07:26 UTC
Labels: 12.1
