### ISSUE TITLE
[FEATURE] Introduce CLI command to create backend user groups

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/Changelog-To-Doc#881] opened 2024-03-21 09:01 UTC
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.1/Feature-103187-AddCliCreateBeUserGroupCommand.html

**Comment by linawolf** [comment] 2024-06-30 14:19
Duplicate of https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/877

**Closed as completed by linawolf** 2024-06-30 14:19 UTC
Labels: Getting Started, 13.1
